### ISSUE TITLE
考虑多VIP支持？

### ISSUE THREAD

**Issue by jiajiaxd** [Fireflyest/GlobalMarket#1]
例如LimitAmountNumVip1:xxx
LimitAmountNumVip2:xxx

**Comment by Fireflyest** [comment]
我的想法是用数字来代替vip，例如market.sell.6就拥有6行的上架空间(6*7)，可能会在后面的版本实现

> 例如LimitAmountNumVip1:xxx LimitAmountNumVip2:xxx
